# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: the laser spectroscopy group
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
    website of the ion spectroscopy group at the university of melbourne
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bieskegroup.github.io" # the base hostname & protocol for your site
github_username:  bieskegroup

# Build settings
markdown: kramdown
